from django.contrib import admin
from DjoSiteDba import models
# Register your models here.
admin.site.register(models.dct_t_l3f1sym_account_primary)
admin.site.register(models.dct_t_l3f1sym_user_right_action)
admin.site.register(models.dct_t_l3f1sym_user_login_session)
admin.site.register(models.dct_t_l3f1sym_account_secondary)
admin.site.register(models.dct_t_l3f1sym_user_right_menu)
admin.site.register(models.dct_t_l3f1sym_menu_code_mapping)
admin.site.register(models.dct_t_l3f1sym_user_right_project)
admin.site.register(models.dct_t_l3f2cm_pg_common)
admin.site.register(models.dct_t_l3f2cm_project_common)
admin.site.register(models.dct_t_l3f2cm_device_common)
admin.site.register(models.dct_t_l3f2cm_favour_site)
admin.site.register(models.dct_t_l2snr_sensor_type)
admin.site.register(models.dct_t_l2snr_dust)
admin.site.register(models.dct_t_l2snr_noise)
admin.site.register(models.dct_t_l2snr_temperature)
admin.site.register(models.dct_t_l2snr_humidity)
admin.site.register(models.dct_t_l2snr_winddir)
admin.site.register(models.dct_t_l2snr_windspd)
admin.site.register(models.dct_t_l2snr_picture)
admin.site.register(models.dct_t_l3f2cm_project_aqyc)
admin.site.register(models.dct_t_l3f2cm_device_aqyc)
admin.site.register(models.dct_t_l3f3dm_current_report_aqyc)
admin.site.register(models.dct_t_l3f3dm_minute_report_aqyc)
admin.site.register(models.dct_t_l3f3dm_alarm_report_aqyc)
admin.site.register(models.dct_t_l3f3dm_current_report_fhys)
admin.site.register(models.dct_t_l3f3dm_minute_report_fhys)
admin.site.register(models.dct_t_l3f2cm_project_fstt)
admin.site.register(models.dct_t_l3f2cm_site_fstt)
admin.site.register(models.dct_t_l3f2cm_device_fstt)
# admin.site.register(models.dct_t_l3f3dm_current_report_fhys)
# admin.site.register(models.dct_t_l3f3dm_current_report_fhys)
# admin.site.register(models.dct_t_l3f3dm_current_report_fhys)
# admin.site.register(models.dct_t_l3f3dm_current_report_fhys)
# admin.site.register(models.dct_t_l3f3dm_current_report_fhys)
# admin.site.register(models.dct_t_l3f3dm_current_report_fhys)