# Generated by Django 2.1a1 on 2018-06-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dct_t_l2snr_dust',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('tsp', models.FloatField(blank=True, default=0, verbose_name='TSP')),
                ('pm01', models.FloatField(blank=True, default=0, verbose_name='PM0.1')),
                ('pm25', models.FloatField(blank=True, default=0, verbose_name='PM2.5')),
                ('pm10', models.FloatField(blank=True, default=0, verbose_name='PM10')),
                ('dataflag', models.CharField(max_length=1)),
                ('report_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l2snr_humidity',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('humidity', models.FloatField(blank=True, default=0, verbose_name='湿度值')),
                ('dataflag', models.CharField(max_length=1)),
                ('report_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l2snr_noise',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('noise', models.FloatField(blank=True, default=0, verbose_name='噪声')),
                ('dataflag', models.CharField(max_length=1)),
                ('report_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l2snr_picture',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('dataflag', models.CharField(max_length=1)),
                ('report_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l2snr_sensor_type',
            fields=[
                ('snr_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('snr_name', models.CharField(max_length=15)),
                ('value_min', models.FloatField(blank=True, default=0, verbose_name='量程最小值')),
                ('value_max', models.FloatField(blank=True, default=0, verbose_name='量程最大值')),
                ('snr_model', models.CharField(max_length=20)),
                ('snr_vendor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l2snr_temperature',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(blank=True, default=0, verbose_name='温度值')),
                ('dataflag', models.CharField(max_length=1)),
                ('report_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l2snr_winddir',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('windir', models.FloatField(blank=True, default=0, verbose_name='风向')),
                ('dataflag', models.CharField(max_length=1)),
                ('report_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l2snr_windspd',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('windspd', models.FloatField(blank=True, default=0, verbose_name='风速')),
                ('dataflag', models.CharField(max_length=1)),
                ('report_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f1sym_account_primary',
            fields=[
                ('uid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('login_name', models.CharField(db_index=True, max_length=20)),
                ('pass_word', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('menu_group', models.IntegerField(default=0)),
                ('grade_lever', models.IntegerField(blank=True, null=True)),
                ('red_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f1sym_menu_code_mapping',
            fields=[
                ('menu_code', models.IntegerField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f1sym_user_right_action',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('action_code', models.IntegerField(unique=True)),
                ('action_name', models.CharField(max_length=20)),
                ('l1_auth', models.BooleanField(blank=True, default=0)),
                ('l2_auth', models.BooleanField(blank=True, default=0)),
                ('l3_auth', models.BooleanField(blank=True, default=0)),
                ('l4_auth', models.BooleanField(blank=True, default=0)),
                ('l5_auth', models.BooleanField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f1sym_user_right_menu',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('menu_group', models.IntegerField(default=0)),
                ('menu_name', models.CharField(max_length=20)),
                ('menu_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f1sym_menu_code_mapping')),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f1sym_user_right_project',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('auth_type', models.IntegerField(default=0)),
                ('auth_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_device_common',
            fields=[
                ('dev_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('socket_id', models.IntegerField(blank=True, null=True)),
                ('hw_type', models.IntegerField(blank=True, null=True)),
                ('hw_ver', models.IntegerField(blank=True, null=True)),
                ('sw_rel', models.IntegerField(blank=True, null=True)),
                ('sw_ver', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_favour_site',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_pg_common',
            fields=[
                ('pg_code', models.AutoField(primary_key=True, serialize=False)),
                ('pg_name', models.CharField(max_length=20)),
                ('pg_creator', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('superintendent', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_project_common',
            fields=[
                ('prj_code', models.AutoField(primary_key=True, serialize=False)),
                ('prj_name', models.CharField(max_length=20)),
                ('prj_creator', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('superintendent', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_site_common',
            fields=[
                ('site_code', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=20)),
                ('site_creator', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('superintendent', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f3dm_alarm_report_aqyc',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('alarmflag', models.CharField(max_length=1)),
                ('alarmseverity', models.IntegerField(blank=True, default=0)),
                ('alarmcontent', models.IntegerField(blank=True, default=0)),
                ('alarmtype', models.IntegerField(blank=True, default=0)),
                ('clearflag', models.IntegerField(blank=True, default=0)),
                ('causeid', models.IntegerField(blank=True, default=0)),
                ('tsgen', models.DateTimeField(auto_now_add=True)),
                ('tsclose', models.DateTimeField(blank=True, null=True)),
                ('alarmpic', models.CharField(max_length=100)),
                ('alarmproc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f3dm_current_report_aqyc',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('tsp', models.FloatField(default=0, verbose_name='TSP')),
                ('pm01', models.FloatField(default=0, verbose_name='PM0.1')),
                ('pm25', models.FloatField(default=0, verbose_name='PM2.5')),
                ('pm10', models.FloatField(default=0, verbose_name='PM10')),
                ('noise', models.FloatField(default=0, verbose_name='噪声')),
                ('temperature', models.FloatField(default=0, verbose_name='温度')),
                ('humidity', models.FloatField(default=0, verbose_name='湿度')),
                ('winddir', models.FloatField(default=0, verbose_name='风向')),
                ('windspd', models.FloatField(default=0, verbose_name='风速')),
                ('rain', models.FloatField(default=0, verbose_name='雨量')),
                ('airpresure', models.FloatField(default=0, verbose_name='气压')),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f3dm_current_report_fhys',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('battvalue', models.FloatField(blank=True, default=0, verbose_name='电池电量值')),
                ('fallvalue', models.FloatField(blank=True, default=0, verbose_name='倾斜角度值')),
                ('tempvalue', models.FloatField(blank=True, default=0, verbose_name='温度值')),
                ('humidvalue', models.FloatField(blank=True, default=0, verbose_name='湿度值')),
                ('rssivalue', models.FloatField(blank=True, default=0, verbose_name='信号强度值')),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f3dm_minute_report_aqyc',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateTimeField(auto_now=True)),
                ('tsp', models.FloatField(default=0, verbose_name='TSP')),
                ('pm01', models.FloatField(default=0, verbose_name='PM0.1')),
                ('pm25', models.FloatField(default=0, verbose_name='PM2.5')),
                ('pm10', models.FloatField(default=0, verbose_name='PM10')),
                ('noise', models.FloatField(default=0, verbose_name='噪声')),
                ('temperature', models.FloatField(default=0, verbose_name='温度')),
                ('humidity', models.FloatField(default=0, verbose_name='湿度')),
                ('winddir', models.FloatField(default=0, verbose_name='风向')),
                ('windspd', models.FloatField(default=0, verbose_name='风速')),
                ('rain', models.FloatField(default=0, verbose_name='雨量')),
                ('airpresure', models.FloatField(default=0, verbose_name='气压')),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f3dm_minute_report_fhys',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateTimeField(auto_now=True)),
                ('battvalue', models.FloatField(blank=True, default=0, verbose_name='电池电量值')),
                ('fallvalue', models.FloatField(blank=True, default=0, verbose_name='倾斜角度值')),
                ('tempvalue', models.FloatField(blank=True, default=0, verbose_name='温度值')),
                ('humidvalue', models.FloatField(blank=True, default=0, verbose_name='湿度值')),
                ('rssivalue', models.FloatField(blank=True, default=0, verbose_name='信号强度值')),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f1sym_account_secondary',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DjoSiteDba.dct_t_l3f1sym_account_primary')),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('true_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '第三人')])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=11, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f1sym_user_login_session',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DjoSiteDba.dct_t_l3f1sym_account_primary')),
                ('session_id', models.CharField(max_length=10)),
                ('timestamp', models.IntegerField(default=1530071486.9560595, verbose_name='更新时间戳')),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_device_aqyc',
            fields=[
                ('dev_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DjoSiteDba.dct_t_l3f2cm_device_common')),
                ('mac_addr', models.CharField(max_length=20)),
                ('cam_url', models.CharField(max_length=100)),
                ('ctrl_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_device_fstt',
            fields=[
                ('dev_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DjoSiteDba.dct_t_l3f2cm_device_common')),
                ('cam_url', models.CharField(max_length=100)),
                ('ctrl_url', models.CharField(max_length=100)),
                ('ctrl2_port', models.IntegerField(blank=True, null=True)),
                ('rtsp2_port', models.IntegerField(blank=True, null=True)),
                ('ctrl3_port', models.IntegerField(blank=True, null=True)),
                ('rtsp3_port', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_project_aqyc',
            fields=[
                ('prj_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DjoSiteDba.dct_t_l3f2cm_project_common')),
                ('eng_code', models.CharField(max_length=50)),
                ('eng_name', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(max_length=5)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('contractors', models.CharField(blank=True, max_length=50, null=True)),
                ('eng_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('site_area', models.FloatField(blank=True, null=True)),
                ('building_area', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=2, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=0)),
                ('eng_status', models.BooleanField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_project_fstt',
            fields=[
                ('prj_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DjoSiteDba.dct_t_l3f2cm_project_common')),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_site_fstt',
            fields=[
                ('site_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DjoSiteDba.dct_t_l3f2cm_site_common')),
                ('order_no', models.CharField(max_length=10)),
                ('tower_sn', models.CharField(max_length=10)),
                ('tower_code', models.CharField(max_length=15)),
                ('tower_type', models.IntegerField(blank=True, default=0)),
                ('tower_conf', models.IntegerField(blank=True, default=0)),
                ('tower_date', models.DateTimeField(blank=True, default=0)),
                ('install_date', models.DateTimeField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_fhys',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_fhys',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_site_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_site_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_fhys',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_fhys',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_site_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_site_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_alarm_report_aqyc',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_alarm_report_aqyc',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_site_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_site_common',
            name='prj_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_project_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_project_common',
            name='pg_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_pg_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_favour_site',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_site_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_favour_site',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f1sym_account_primary'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_device_common',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_site_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f1sym_user_right_project',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f1sym_account_primary'),
        ),
        migrations.AddField(
            model_name='dct_t_l2snr_windspd',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l2snr_winddir',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l2snr_temperature',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l2snr_picture',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_site_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l2snr_noise',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l2snr_humidity',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l2snr_dust',
            name='dev_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjoSiteDba.dct_t_l3f2cm_device_common'),
        ),
    ]
