# Generated by Django 2.1a1 on 2018-06-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_l3f1sym_account_primary',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('login_name', models.CharField(db_index=True, max_length=20)),
                ('pass_word', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('menu_group', models.IntegerField(default=0)),
                ('grade_lever', models.IntegerField(null=True)),
                ('red_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_l3f1sym_menu_code_mapping',
            fields=[
                ('menu_code', models.IntegerField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='t_l3f1sym_user_action',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('action_code', models.IntegerField(unique=True)),
                ('action_name', models.CharField(max_length=20)),
                ('l1_auth', models.BooleanField(default=0)),
                ('l2_auth', models.BooleanField(default=0)),
                ('l3_auth', models.BooleanField(default=0)),
                ('l4_auth', models.BooleanField(default=0)),
                ('l5_auth', models.BooleanField(default=0)),
                ('l6_auth', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='t_l3f1sym_user_right_menu',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('menu_group', models.IntegerField(default=0)),
                ('menu_name', models.CharField(max_length=20)),
                ('menu_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xhzn.t_l3f1sym_menu_code_mapping')),
            ],
        ),
        migrations.CreateModel(
            name='t_l3f1sym_user_right_project',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('auth_type', models.IntegerField(default=0)),
                ('auth_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='t_l3f2cm_device_common',
            fields=[
                ('dev_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('socket_id', models.IntegerField(null=True)),
                ('hw_type', models.IntegerField(null=True)),
                ('hw_ver', models.IntegerField(null=True)),
                ('sw_rel', models.IntegerField(null=True)),
                ('sw_ver', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_l3f2cm_pg_common',
            fields=[
                ('pg_code', models.IntegerField(primary_key=True, serialize=False)),
                ('pg_name', models.CharField(max_length=20)),
                ('pg_creator', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('superintendent', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_l3f2cm_project_common',
            fields=[
                ('prj_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prj_name', models.CharField(max_length=20)),
                ('prj_creator', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('superintendent', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('comments', models.TextField(null=True)),
                ('pg_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xhzn.t_l3f2cm_pg_common')),
            ],
        ),
        migrations.CreateModel(
            name='t_l3f2cm_site_common',
            fields=[
                ('site_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=20)),
                ('site_creator', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('superintendent', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('comments', models.TextField(null=True)),
                ('prj_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xhzn.t_l3f2cm_project_common')),
            ],
        ),
        migrations.CreateModel(
            name='t_l3f1sym_account_secondary',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='xhzn.t_l3f1sym_account_primary')),
                ('nick_name', models.CharField(max_length=20, null=True)),
                ('true_name', models.CharField(max_length=20, null=True)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '第三人')], null=True)),
                ('age', models.IntegerField(null=True)),
                ('telephone', models.CharField(max_length=11, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='t_l3f2cm_device_common',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xhzn.t_l3f2cm_site_common'),
        ),
        migrations.AddField(
            model_name='t_l3f1sym_user_right_project',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xhzn.t_l3f1sym_account_primary'),
        ),
    ]
